skovy/typed-scss-modules

lib/typescript/class-names-to-type-definition.ts
package.json
yarn.lock

* Filter out classnames that are reserved javascript keywords in either es5 or es6 javascript.
* Output a warning for each classname filtered out, with a suggestion to use default exports instead if the filtered out classname was required as part of the export.
Use case: using bootstrap-sass (v3), the classname "in" is created. Since this is a reserved keyword in javascript, the named export definition file that was being created was invalid, breaking the ability to compile the project. However, the user is not likely to be using this as 'styles.in' anywhere, so removing the invalid export does not prevent the user from access to the classnames that they do use. The warning message both informs the user that a classname was excluded, and provides instructions on how to work around the …

[Bugfix]: Don't output named exports that are javascript reserved words.

---

README.md
lib/cli.ts
lib/sass/file-to-class-names.ts

Implements #9.
When using Webpack with sass-loader to compile scss files, the standard import syntax is `~package-name/path/to/file`, where `~` is then replaced with the string `node_modules/`. In this case, it can become very bloated to have to individually specify each imported scss file alias for these imports. Being able to define a prefix value to replace within the filename string means that a single prefix can be used to match the sass-loader/webpack import syntax for all scss imports.

[Feature]: Implement ability to define alias prefixes.

---

README.md
__tests__/core/generate.test.ts
__tests__/dashes.scss
__tests__/dashes.scss.d.ts
__tests__/main.test.ts
__tests__/sass/file-to-class-names.test.ts
lib/sass/file-to-class-names.ts
lib/typescript/class-names-to-type-definition.ts

* dashes - matches the "dashesOnly" option from css-loader where only classNames containing a dash are converted to camel-case.
* none - projects created with create-react-app v2 use a webpack config that does not modify the classnames at all. This means that in order for webpack to find the generated classNames, the exported type names for classes must not be altered. Using `--exportType default` is required if the user has any classNames containing dashes (dashes are identified as invalid names if `--exportType named` is used and generate a warning that the classname containing a dash has been excluded).
I've tried to document how each of the nameFormat options change the original classnames, but I wasn't able to see what the difference was between `param` and `kebab`. Please let me …

Add 2 nameFormat options for use with Webpack.

---

README.md
__tests__/typescript/class-names-to-type-definitions.test.ts
examples/default-export/feature-a/index.ts
examples/default-export/feature-a/style.scss.d.ts
lib/typescript/class-names-to-type-definition.ts

Inspired from https://github.com/skovy/typed-scss-modules/issues/19.
It may be useful to have direct access to the `Styles` interface or assigning a specific class name to a variable.

Export the Styles interface + ClassNames union

---

README.md
__tests__/core/generate.test.ts
__tests__/core/list-different.test.ts
__tests__/core/write-file.test.ts
__tests__/main.test.ts
lib/cli.ts
lib/core/types.ts
lib/core/watch.ts

This adds an option to skip the initial run when using the watch param. This is useful when running concurrently with some other script (another watch, for instance), but this should finish first the first time. So you run this first, then run watch with skip initial true.

feat(option): allow to skip initial build in watch

---

__tests__/main.test.ts
lib/main.ts
package.json

Resolves https://github.com/skovy/typed-scss-modules/issues/28
Chokidar couldn't watch files with backslashes in path, they should be replaced with forward slashes 
Quote from chokidar readme:
> Note: globs must not contain windows separators (\\), because that's how they work by the standard — you'll need to replace them with forward slashes (/).

fix watch option not working on windows

---

.travis.yml
README.md
__tests__/cli.test.ts
__tests__/core/generate.test.ts
__tests__/core/list-different.test.ts
__tests__/core/write-file.test.ts
__tests__/helpers/index.ts
__tests__/implementations/get-default-implementation.test.ts
__tests__/implementations/get-implementation.test.ts
__tests__/main.test.ts
__tests__/sass/file-to-class-names.test.ts
jest.config.js
lib/cli.ts
lib/core/generate.ts
lib/implementations/index.ts
lib/sass/file-to-class-names.ts
package.json
yarn.lock

Resolves https://github.com/skovy/typed-scss-modules/issues/43.
The Dart SASS and Node SASS implementations should be compatible (tested via unit tests) and folks may choose to use those interchangably. However, `typed-scss-modules` currently doesn't support both options.
- Use the package name passed in as the `implementation` option (`sass` or `node-sass`).
- Else, try to load either package and use the implementation (`node-sass` or `sass`) defined in `node_modules`. If they both exist, it will use `node-sass`.
- Else, if none are found, use `node-sass` (probably will error but we need some implementation).
- Added a `console.log` to the `renderSync` methods in `node-sass` (`lib/index.js:387`) and `sass` (`sass.dart.js:10684`) packages to validate the proper packages were being …

Support the Dart SASS package

---

README.md
__tests__/core/generate.test.ts
__tests__/core/list-different.test.ts
__tests__/core/write-file.test.ts
__tests__/main.test.ts
__tests__/typescript/class-names-to-type-definitions.test.ts
lib/cli.ts
lib/core/list-different.ts
lib/core/types.ts
lib/core/write-file.ts
lib/typescript/class-names-to-type-definition.ts
lib/typescript/index.ts

I'm not sure if this would be useful to anybody else, but I wanted to be able to specify whether to use single or double quotes in the type definitions. Typically my tslint.json is set up for double quotes, so I have a bunch of TS errors showing from each of these files.

feat(quotetype): implement the quoteType option

---

README.md
__tests__/typescript/class-names-to-type-definitions.test.ts
examples/default-export/README.md
examples/default-export/feature-a/style.scss.d.ts
lib/cli.ts
lib/core/list-different.ts
lib/typescript/class-names-to-type-definition.ts
lib/typescript/get-type-definition-path.ts

Rel: https://github.com/skovy/typed-scss-modules/issues/71
Before we were unable to do this:
```typescript
export interface Styles {
'classname--first': string;
'classname--second': string;
}
function foo(bar: Record<string, string>){
return Object.keys(bar);
}
```
Because an interface does not allow being cast as a wider type. This fixes that by using types instead of interfaces:
```typescript
export type Styles = {
'classname--first': string;
'classname--second': string;
}
```
BREAKING CHANGE: this can interfere with how others use their default exported classnames
PS: added some typo fixes in as well

fix(export-default): export a type instead of an interface Fixes #71

---

__tests__/main.test.ts
__tests__/sass/file-to-class-names.test.ts
lib/sass/file-to-class-names.ts

Implements sort class names change as a forced default as opposed to optionally like in #79 
I'm a bit unsure what the `scss.d.ts` files in the test folder are for and if I should change those?
BREAKING: This changes the current behavior and scss.d.ts files should probably be regenerated.

feat: sort class names

---

README.md
__tests__/core/__snapshots__/attemptPrettier.test.ts.snap
__tests__/core/attemptPrettier.test.ts
lib/core/attemptPrettier.ts
lib/core/canResolvePrettier.ts
lib/core/write-file.ts
package.json
yarn.lock

I wanted to take a stab at #69 because I was curious how to solve config loading, turns out prettier has a function for that, [resolveConfig](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options), which made this pretty easy to add. I spent more time on the tests than I care to admit, because I couldn't figure out why `require.resolve` couldn't be mocked, found a workaround when moving that to a module. I don't think calling the promise like I do in `writeFile` is very nice (nested promises), so I started to convert to async / await, but decided that would be too much of a change here, and reverted. Also, this behavior should probably be documented somehow, but unsure where to add that and how to describe it. It could also be an option, but I would bet that those …

feat: use prettier to format files before save if available

---

README.md
__tests__/cli.test.ts
__tests__/core/attemptPrettier.test.ts
__tests__/core/generate.test.ts
__tests__/core/list-different.test.ts
__tests__/core/write-file.test.ts
__tests__/main.test.ts
__tests__/typescript/class-names-to-type-definitions.test.ts
examples/basic/feature-a/style.scss.d.ts
examples/basic/feature-b/style.scss.d.ts
examples/default-export/feature-a/style.scss.d.ts
lib/cli.ts
lib/core/types.ts
lib/typescript/class-names-to-type-definition.ts
lib/typescript/index.ts

Inspired by the [banner option in similar typings-for-css-modules-loader](https://github.com/Jimdo/typings-for-css-modules-loader#banner-option), this allows users to prepend any string to the top of their output files for the sake of documentation.
Example usage:
```
tsm src --banner '// This is a generated file.\n// Please do not edit this file.\n'
```
would result in files with output:
```typescript
// This is a generated file.
// Please do not edit this file.
export type Styles = {
...
```

feat(banner): allows user to append banner / comment to the top of every output file

---

lib/typescript/class-names-to-type-definition.ts

Removes reference of just \n since windows adds a \r in front of
each \n. So to make it os specific we will utilize the os dependent
end of line string.
This seeks to address https://github.com/skovy/typed-scss-modules/issues/67

fix: addresses CRLF vs LF issue on windows

---

README.md
__tests__/core/generate.test.ts
__tests__/core/list-different.test.ts
__tests__/core/write-file.test.ts
__tests__/main.test.ts
lib/cli.ts
lib/core/list-different.ts
lib/core/types.ts
lib/core/write-file.ts

This change was inspired by the `--update` option from [cpx](https://github.com/mysticatea/cpx). Without this option, `tsm` was overwriting type definition files in my project, causing TypeScript recompilations. In a large project, this can cause some significant performance problems.
I purposefully didn't update the README or add test coverage yet because I'd like feedback on the general approach first. I'm happy to add these changes after collecting initial thoughts! Does this idea have the potential to make it into a release? Thanks!

feat: add update option to prevent unnecessary file updates

---

__tests__/typescript/class-names-to-type-definitions.test.ts
lib/typescript/class-names-to-type-definition.ts

BREAKING CHANGE: when using exportType default, the output will now have a semicolon after the type.
Fixes https://github.com/skovy/typed-scss-modules/issues/111

fix(formatting): add missing semicolon after type

---

__tests__/core/generate.test.ts
__tests__/dummy-styles/composes.scss
__tests__/dummy-styles/composes.scss.d.ts
__tests__/main.test.ts
__tests__/sass/file-to-class-names.test.ts
lib/sass/source-to-class-names.ts

Fixes the issue described in https://github.com/skovy/typed-scss-modules/issues/57
This PR adds support for generating definition files for an scss module like this:
```
.composed-class {
composes: nested-styles from "./nested-styles/style.scss";
color: red;
}
```
Support is achieved by passing a dummy `PathFetcher` to css-module-loader-core.
A dummy implementation is sufficient as the composition does not add new class names to the module.
css-module-loader-core directly passes the returned object to icss-replace-symbols as the `replacements` map. That library will simply skip replacing a symbol when the key is not present in the `replacements` map: https://github.com/css-modules/icss-utils/blob/master/src/replaceValueSymbols.js#L7-L17

Support "Composing from other files" css module feature.

---

__tests__/cli.test.ts
__tests__/typescript/class-names-to-type-definitions.test.ts
examples/basic/feature-a/style.scss.d.ts
examples/basic/feature-b/style.scss.d.ts
lib/typescript/class-names-to-type-definition.ts

Fixes https://github.com/skovy/typed-scss-modules/issues/117
Additionally, this PR updates both cases to push each line into an array, and then join using newlines. Longer-term might be nice to use babel and construct a proper AST and avoid the manual string construction, but hopefully, now both are handled consistently these types of issues due to the difference in logic will be easier to avoid (and not overlook).

Fix banner formatting

---

__tests__/core/list-different.test.ts
__tests__/core/list-different/no-generated.scss
lib/core/list-different.ts

When running `tsm` with option `--listDifferent`, and all type definition files are not yet generated, code raises an error that is not catch.
Even if type definition file does not exist, script exits with 0.
This PR fixes this issue by checkig previously if the file exists. If not, it raises an error.

Fix missing type file using --listDifferent option

---

README.md
__tests__/cli.test.ts
examples/basic/README.md
examples/default-export/README.md
package.json

BREAKING CHANGE. This package's bin (CLI) name was changed from 'tsm' to 'typed-scss-modules'
Resolves https://github.com/skovy/typed-scss-modules/issues/134

Rename package bin

---

README.md
__tests__/load.test.ts
__tests__/sass/importer.test.ts
lib/implementations/index.ts
lib/sass/importer.ts
package.json
yarn.lock

BREAKING CHANGE: sass updated to 1.49.7 and node-sass updated to 4.12.0
- Upgrade to latest `sass` version: https://www.npmjs.com/package/sass
- Upgrade to last `node-sass` version with node v12 support: https://github.com/sass/node-sass/releases/tag/v4.12.0
This likely won't cause any breaking changes but since peer dependency versions were updated it was released as breaking change.

Upgrade sass & node-sass

---

__tests__/load.test.ts
examples/config-file/typed-scss-modules.config.js
lib/load.ts

Resolves https://github.com/skovy/typed-scss-modules/issues/157
For some reason using `coerce` with `yargs` will always set a value, even `undefined`. I removed `coerce` but there is no other clean way to cast to the correct type. Instead, it was much easier to simply remove `undefined` values from the CLI options and make this more future proof as well.

fix: alias and aliasPrefixes in config file

---

.gitignore
lib/index.ts
package.json
tsconfig.json

It would be really useful to be able to programmatically invoke `tsm` as opposed to running it via a CLI command.
People can currently do this in a hacky way by importing the `main` function from `typed-scss-modules/dist/lib/main.js`.
This PR adds a real entry point and adds the exporting of type declarations.
Example usage: `import tsm from 'typed-scss-modules';`

feat: export main as tsm

---

lib/sass/file-to-class-names.ts

Remove duplication between 'NameFormat' union type and the array with actual values

fix: cli accepts 'snake' name format option

---

README.md
__tests__/core/list-different.test.ts
__tests__/load.test.ts
__tests__/sass/file-to-class-names.test.ts
lib/cli.ts
lib/load.ts
lib/sass/file-to-class-names.ts
lib/sass/index.ts
lib/typescript/class-names-to-type-definition.ts

* Adds support for multiple name formatters, allowing a user to pass multiple `-n <formatName>` which will generate unique class names accordingly
* Adds support for the formatter's name `all` which includes all formatters, excluding `all` and `none`.
* Adds tests for the support of such feature.
* Refactors `lib/sass/file-to-class-names.ts` code to a more modern approach using `async ... await` and improves the types.

Adds support for multiple name formatters

---

__tests__/core/list-files-and-perform-sanity-check.test.ts
lib/core/generate.ts
lib/core/list-files-and-perform-sanity-checks.ts
lib/core/watch.ts

I noticed that a warning is printed if 0 files match the pattern in "non-watch" mode, but the warning is not printed in watch mode, it just says "Watching files...". This could be confusing if you are attempting to use watch mode and have passed the wrong glob.

feat: perform sanity check in watch mode

---

package.json
yarn.lock

As you may know, there are frequently issues compiling older versions of node-sass. It failed to build with crazy C++ compilation errors when I ran `yarn install` in this repository. This PR upgrades node-sass to the latest which installed cleanly.

chore: upgrade node-sass to latest

---

package.json

Update package.json to support node-sass 8.x as peer dependency

feat(node-sass): support 8.x as a peer dependency

---

README.md
__tests__/__snapshots__/main.test.ts.snap
__tests__/core/write-file.test.ts
__tests__/dummy-styles/alias-prefixes.scss.d.ts
__tests__/dummy-styles/aliases.scss.d.ts
__tests__/dummy-styles/complex.scss.d.ts
__tests__/dummy-styles/composes.scss.d.ts
__tests__/dummy-styles/dashes.scss.d.ts
__tests__/dummy-styles/invalid.scss.d.ts
__tests__/dummy-styles/nested-styles/style.scss.d.ts
__tests__/dummy-styles/style.scss.d.ts
__tests__/main.test.ts
__tests__/typescript/class-names-to-type-definitions.test.ts
examples/basic/feature-a/style.scss.d.ts
examples/basic/feature-b/style.scss.d.ts
examples/output-folder/__generated__/examples/output-folder/feature-a/a.scss.d.ts
examples/output-folder/__generated__/examples/output-folder/feature-b/b.scss.d.ts
examples/output-folder/__generated__/examples/output-folder/feature-c/c.scss.d.ts
examples/output-folder/__generated__/examples/output-folder/feature-c/nested/nested.scss.d.ts
lib/typescript/class-names-to-type-definition.ts

This will prevent some errors in Esbuild, where it expects the constants to be initialised even though they are in the .d.ts files.
This error is fixed after this PR:
```js
Error: Transform failed with 1 error:
<stdin>:1:13: ERROR: The constant "confirmationInput" must be initialized
at failureErrorWithLog (/home/aminya/test/node_modules/esbuild/lib/main.js:1624:15)
at /home/aminya/test/node_modules/esbuild/lib/main.js:1413:29
at /home/aminya/test/node_modules/esbuild/lib/main.js:678:9
at handleIncomingPacket (/home/aminya/test/node_modules/esbuild/lib/main.js:775:9)
at Socket.readFromStdout (/home/aminya/test/node_modules/esbuild/lib/main.js:644:7)
at Socket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk …
```

fix: export the named types as declared

---

__tests__/prettier/prettier.test.ts
__tests__/typescript/class-names-to-type-definitions.test.ts
lib/core/list-different.ts
lib/core/write-file.ts
lib/prettier/index.ts
lib/typescript/class-names-to-type-definition.ts

Resolves #219.
Recent versions of Prettier have changed the logic for resolving the config. [This line](https://github.com/prettier/prettier/blob/d970deed6b6cabe21fdb35249265d766932b5718/src/config/resolve-config.js#L36) appears to be the culprit:
```js
const directory = file ? path.dirname(path.resolve(file)) : undefined;
```
When `attemptPrettier` is called, it passes `process.cwd()` as the "file" in the snippet above. It's common for `typed-scss-modules` to be executed from the project root, so the config search starts outside the project root and doesn't find anything.
`attemptPrettier` resolves the prettier config based on the generated file path instead of `process.cwd()`.

fix: resolve Prettier config based on generated file

---

README.md
__tests__/core/generate.test.ts
__tests__/core/list-different.test.ts
__tests__/core/list-files-and-perform-sanity-check.test.ts
__tests__/core/write-file.test.ts
__tests__/load.test.ts
lib/cli.ts
lib/core/types.ts
lib/load.ts
lib/typescript/get-type-definition-path.ts

This PR adds an option named `allowArbitraryExtensions` (command line: `--allowArbitraryExtensions`).
When enabled, `typed-scss-modules` will output generated type definition filenames that are be compatible with the "arbitrary file extensions" feature that was introduced in TypeScript 5.0. See [the docs](https://www.typescriptlang.org/tsconfig#allowArbitraryExtensions) for more info.
In essence, the `*.scss.d.ts` extension now becomes `*.d.scss.ts` so that you can import SCSS modules in projects using ESM module resolution.
(Inspired by [the equivalent feature](https://github.com/Quramy/typed-css-modules?tab=readme-ov-file#arbitrary-file-extensions) from `typed-css-modules`.)

feat: add --allowArbitraryExtensions option (compatible with the TS 5.0 feature of the same name)

---

package-lock.json
package.json

This PR upgrades the following packages to address an issue in my environment when trying to use the [config options](https://github.com/skovy/typed-scss-modules?tab=readme-ov-file#config-options) of this package:
- bundle-require: `^3.0.4` -> `^4.0.4`
- esbuild: `^0.14.21` -> `^0.17.0`
When using the config options in my environment, I encountered the following error:
```
Error: Build failed with 1 error:
/projectA/node_modules/esbuild/lib/main.js:256:12: ERROR: Invalid option in build() call: "watch"
```
This error appears to be [caused by the removal of the watch option in esbuild starting from version 0.17.0](https://github.com/evanw/esbuild/releases/tag/v0.17.0). It seems that [this PR](https://github.com/egoist/bundle-require/pull/36) in the bundle-require repository has addressed …

fix: upgrade bundle require
